### PR TITLE
Siraola/integration UI

### PR DESCRIPTION
**Pull request by blam92**
#### JIRA LINK ####

PSV-138

#### CHANGES ####

Tried to separate changes in appropriate commits as much as possible so its easier to review:

- Integration of all UI pieces
- Displaying seqIds in different lines
- Ability to edit patent with new schema. User has a dropdown to select the claimed residues for each seq id
- Updated table to show claimed residues and mentioned residues as well as some new fields available in db schema
- Baseline is gone! Chart is showing all aminoacids for each patent
- Chart tooltip is showing real data for that position including seq id
- Chart shows aminoacid letters for claimed residues too with a one letter code and if hovered you can see the three letter code. (Tested showing the three letter code in the chart but it is way to small to fit three letters so sticking with one there and three in tooltip)

### CODE REVIEW

**Comment by blam92** [comment]
image

**Comment by blam92** [comment]
image

**Comment by blam92** [comment]
Case were we have references to the same seq id on description and claims. Edit feature updates correctly based on user selection

image

**Review by kaliweh — APPROVED** [review]
Let's do this

**Pull request merged**
